### PR TITLE
Merge in rummager changes

### PR DESCRIPTION
**Pull request by sihugh**
See commits for details

### CODE REVIEW

**Comment by leenagupte** [comment]
@sihugh My changes have already been added here: https://github.com/alphagov/search-api/pull/17

**Comment by sophiebrown01** [comment]
I have also since merged in a bunch of changes from Rummager (including many here). A bit of weirdness did occur but have confirmed with Bruce that we can sort this out when merging everything back into Rummager.

**Comment by barrucadu** [comment]
I think history strangeness here is fine, the way we're doing the repository shuffling is that we're going to merge our (search perf team's) changes into the rummager repository and remove this one.

So history here can be as messy as it needs to be.

**Comment by sihugh** [comment]
Shall I close this then?  It seems to have been overtaken by other PRs too

**Comment by barrucadu** [comment]
Sure, I think we're currently up to date with rummager

**Pull request closed without merging**
